"use client";

// import type { Metadata } from "next";
import { useEffect, useState } from "react";
import "./globals.css";
import { Tiro_Bangla } from "next/font/google";
import Providers from "@/lib/Provider";
import { Toaster } from "react-hot-toast";
import ScrollToTop from "@/components/ScrolltoTop/ScrolltoTop";

const tiro_Bangla = Tiro_Bangla({
  weight: "400",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "sarabelanews24",
//   description: "Generated by create next app",
//   icons: {
//     icon: "/favicon.ico",
//   },
// };

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const [theme, setTheme] = useState("light");

  useEffect(() => {
    // Get theme from localStorage
    const storedTheme = localStorage.getItem("theme") || "light";
    setTheme(storedTheme);

    // Apply the theme class to <html>
    if (storedTheme === "dark") {
      document.documentElement.classList.add("dark");
    } else {
      document.documentElement.classList.remove("dark");
    }
  }, []);

  return (
    <html lang="en" className={theme === "dark" ? "dark" : ""}>
      <Providers>
        <body
          className={`bg-white dark:bg-gray-800 dark:text-white ${tiro_Bangla.className}`}
        >
          {children}
          <Toaster />
          <ScrollToTop />
        </body>
      </Providers>
    </html>
  );
}
